# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'YYFMDBAdapterDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for YYFMDBAdapterDemo
  pod 'AFNetworking' , '~>  3.0.4'
  pod 'YYModel'
  pod 'FMDB', '~> 2.6.2'
  
  target 'YYFMDBAdapterDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
